### ISSUE TITLE
Can not connect to S3

### ISSUE THREAD

**Issue by rajnish-garg** [NFLabs/zeppelin#422]
I have installed Zeppelin, on my aws EC2 machine to connect to my spark cluster.

Spark Version: Standalone: spark-1.2.1-bin-hadoop1.tgz

I am able to connect to spark cluster but getting following error, when trying to access the file in S3 in my usecase.

Code:

    sc.hadoopConfiguration.set("fs.s3n.awsAccessKeyId", "YOUR_KEY_ID")
    sc.hadoopConfiguration.set("fs.s3n.awsSecretAccessKey","YOUR_SEC_KEY")
    val file = "s3n://<bucket>/<key>"
    val data = sc.textFile(file)
    data.count

file: String = s3n://<bucket>/<key>
data: org.apache.spark.rdd.RDD[String] = s3n://<bucket>/<key> MappedRDD[1] at textFile at <console>:21
ava.lang.NoSuchMethodError: org.jets3t.service.impl.rest.httpclient.RestS3Service.<init>(Lorg/jets3t/service/security/AWSCredentials;)V
    at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.initialize(Jets3tNativeFileSystemStore.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:85)

I have build the Zeppelin by following command:

    mvn clean package -Pspark-1.2.1 -Dhadoop.version=1.0.4 -DskipTests
when I trying to build with hadoop profile "-Phadoop-1.0.4", it is giving warning that it doesn't exist.

I have also tried -Phadoop-1 mentioned in this spark website. but got the same error. 1.x to 2.1.x hadoop-1

http://stackoverflow.com/questions/30884662/why-zeppelin-notebook-is-not-able-to-connect-to-s3

**Comment by bzz** [comment]
please check out #421 (title: PLEASE DO NOT CREATE ISSUES HERE)

>Zeppelin's has moved to Apache incubator. This github repository is not going to be synced to the ASF's one after 20/Mar/2015. Please consider using ASF repo for source code access and JIRA for issues.

>Please use new github repo to create pull-request.
>Github : https://github.com/apache/incubator-zeppelin

>Please create issue on JIRA.
>JIRA : https://issues.apache.org/jira/browse/ZEPPELIN
